version: '3.8'

services:

  app:
    build: .
    image: riyadrb/laravel-banking
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
  
   
  database:
    image: mysql:8.0
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: banking
      MYSQL_ROOT_PASSWORD: password


  server:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


